#ifndef RECCA_CONFIG_H
#define RECCA_CONFIG_H

#define GAME_WIDTH 60
#define GAME_HEIGHT 24

#define MAX_PLAYER_SHOTS 48
#define MAX_ENEMIES 16
#define MAX_ENEMY_SHOTS 40
#define MAX_POWERUPS 6
#define MAX_HIGH_SCORES 5
#define PLAYER_NAME_MAX_LENGTH 10
#define HIGHSCORE_FILE_NAME "highscores.txt"

#define MAX_EFFECTS 16
#define EXPLOSION_DURATION 5
#define STATUS_MESSAGE_LENGTH 40
#define STATUS_MESSAGE_DURATION 70

#define WAVE_BASE_ENEMY_COUNT 8
#define WAVE_SPAWN_INTERVAL 18
#define WAVE_BREAK_FRAMES 80

#define SCORE_RANK_INTERVAL 2500
#define BOSS_SCORE_INTERVAL 1400
#define BOSS_SCORE_INTERVAL_GROWTH 400
#define MINI_BOSS_HEALTH 8
#define STAGE_BOSS_HEALTH 16
#define MINI_BOSS_SCORE 500
#define STAGE_BOSS_SCORE 1000


#define PLAYER_START_LIVES 3
#define PLAYER_START_X (GAME_WIDTH / 2)
#define PLAYER_START_Y (GAME_HEIGHT - 2)
#define PLAYER_INVULNERABLE_FRAMES 45
#define MAX_PLAYER_DRONES 2
#define PLAYER_DRONE_OFFSET_X 4
#define PLAYER_DRONE_OFFSET_Y 1
#define PLAYER_WEAPON_DURATION_FRAMES 515
#define PLAYER_DRONE_DURATION_FRAMES 387
#define PLAYER_CHARGE_MAX 60
#define PLAYER_CHARGE_RELEASE_MIN 25
#define PLAYER_CHARGE_SHIELD_MIN 15
#define CHARGE_SHIELD_RADIUS 1
#define CHARGE_BOMB_RADIUS 6
#define CHARGE_BOMB_DAMAGE 3

#define POWERUP_DROP_DIVISOR 4
#define POWERUP_MOVE_INTERVAL 3

#define PLAYER_SHOT_COOLDOWN 2
#define PLAYER_SHOT_MOVE_INTERVAL 1

#define ENEMY_BASE_MOVE_INTERVAL 4
#define ENEMY_SHOT_BASE_MOVE_INTERVAL 2

#define FRAME_DELAY_MS 40

#endif
