#ifndef RECCA_CONFIG_H
#define RECCA_CONFIG_H

#define GAME_WIDTH 70
#define GAME_HEIGHT 24

#define MAX_PLAYER_SHOTS 16
#define MAX_ENEMIES 12
#define MAX_ENEMY_SHOTS 24

#define MAX_EFFECTS 16
#define EXPLOSION_DURATION 5

#define WAVE_BASE_ENEMY_COUNT 8
#define WAVE_SPAWN_INTERVAL 18
#define WAVE_BREAK_FRAMES 80


#define PLAYER_START_LIVES 3
#define PLAYER_START_X (GAME_WIDTH / 2)
#define PLAYER_START_Y (GAME_HEIGHT - 2)

#define PLAYER_SHOT_COOLDOWN 2
#define PLAYER_SHOT_MOVE_INTERVAL 1

#define ENEMY_BASE_MOVE_INTERVAL 3
#define ENEMY_SHOT_BASE_MOVE_INTERVAL 2

#define FRAME_DELAY_MS 40

#endif
